version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lisaatthemoment
    volumes:
      - pgData:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgData:
